version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    filters:
      branches:
        only: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "xx:xx:xx:xx:11:22:33:44:55:66:77:88:99:xx:xx:xx"
      - checkout
      - run:
          name: bundle
          command: bundle
      - run:
          name: Run deploy scripts
          command: ../scripts/deploy-ghpages.sh
